### ISSUE TITLE
case sensitify issues in web portal searches

### ISSUE THREAD

**Issue by timo11** [specify/webportal-installer#2]
For example: In Express search, or in Advanced Search Collectors, 'Bentley' returns no matches but 'bentley' returns many.

**Comment by benanhalt** [comment]
verified fixed in 700dfd93c89a021c1d5432c941fab2019a1840cf

**Comment by timo11** [comment]
fixed by commit 145c00d0b3cadaaed733d4d88b60849626ad6bf1

Case shouldn't be an issue for advanced search. 

But, for express search, it's possible that catalog numbers starting with 'CAT' won't be matched by the search string 'CAT' because the solr index for catalognumber is case sensitive. It appears that solr 'full text' fields require search strings to be lower-case, but 'string' fields do not. Since express search searches all fields, it seems necessary to search full-text fields with the lower-cased search term and string fields with the exact search term.  As of the fix, express search terms are lower-cased.

**Comment by timo11** [comment]
It looks like case is not an issue for express search either.
