### ISSUE TITLE
Error when trying to build Web Portal

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/webportal-installer#34]
When trying to build a developer's branch of web portal uing the following command:
```
make clean && make
```
I receive the following error

![Screenshot from 2019-12-09 16-47-22](https://user-images.githubusercontent.com/40512816/70479735-a052e500-1aa3-11ea-93a5-a080a4b80e75.png)

```
Traceback (most recent call last):
  File "/home/m001p596/Downloads/webportal-installer-develop/patch_web_xml.py", line 21, in <module>
    from lxml import etree
ImportError: cannot import name etree
/home/m001p596/Downloads/webportal-installer-develop/core.make:33: recipe for target 'web.xml' failed
make[2]: *** [web.xml] Error 1
```

It references to `patch_web_xml.py` file:
![Screenshot from 2019-12-09 16-49-49](https://user-images.githubusercontent.com/40512816/70479885-f0ca4280-1aa3-11ea-983c-ad58f8247f61.png)

Tried [this](https://lxml.de/installation.html) and [this](https://www.odoo.com/forum/help-1/question/odoo11-cannot-import-name-etree-142531), with no result

Any advice on how to solve this issue?

**Comment by benanhalt** [comment]
Looks like you are missing the Python lxml package. If you are using Ubuntu, `sudo apt install python-lxml` should get it.

**Comment by benanhalt** [comment]
We may need to add that to the list of dependencies.

**Comment by maxxxxxdlp** [comment]
Tried the same thing on my mac (web portal developer branch)
<img width="1440" alt="Screen Shot 2019-12-20 at 9 58 07 AM" src="https://user-images.githubusercontent.com/40512816/71267059-4659e700-230f-11ea-93de-752767c67383.png">

Used `"pip install lxml"` to fix this issue. Now I got another problem:
```
Traceback (most recent call last):
  File "/Users/mambo/Downloads/webportal-installer-develop/patch_web_xml.py", line 35, in <module>
    if c.tag.endswith('filter'):
AttributeError: 'cython_function_or_method' object has no attribute 'endswith'
make[2]: *** [web.xml] Error 1
make[1]: *** [cores] Error 2
make: *** [build] Error 2
```

**Comment by maxxxxxdlp** [comment]
Here is my error on Ubuntu when tring to build web portal (master branch)
![Screenshot from 2019-12-20 10-00-35](https://user-images.githubusercontent.com/40512816/71267158-93d65400-230f-11ea-886f-7300ff62ddbe.png)

**Comment by maxxxxxdlp** [comment]
Still was getting the same error on Ubuntu:
```
Traceback (most recent call last):
  File "/home/m001p596/Downloads/webportal-installer-develop/patch_web_xml.py", line 21, in <module>
    from lxml import etree
ImportError: cannot import name etree
/home/m001p596/Downloads/webportal-installer-develop/core.make:33: recipe for target 'web.xml' failed
make[2]: *** [web.xml] Error 1
```
Even after those commands:
```
pip install lxml
sudo pip install lxml
pip install lxml==3.4.2
sudo apt-get install python-lxml
```

Fixed it by changing `"patch_web_xml.py"`
Changed line 22 from:
```
from lxml import etree
```
to
```
try:
  from lxml import etree
  print("running with lxml.etree")
except ImportError:
  try:
    # Python 2.5
    import xml.etree.cElementTree as etree
    print("running with cElementTree on Python 2.5+")
  except ImportError:
    try:
      # Python 2.5
      import xml.etree.ElementTree as etree
      print("running with ElementTree on Python 2.5+")
    except ImportError:
      try:
        # normal cElementTree install
        import cElementTree as etree
        print("running with cElementTree")
      except ImportError:
        try:
          # normal ElementTree install
          import elementtree.ElementTree as etree
          print("running with ElementTree")
        except ImportError:
          print("Failed to import ElementTree from any known place")
```
![Screenshot from 2019-12-20 10-03-49](https://user-images.githubusercontent.com/40512816/71267385-06dfca80-2310-11ea-8a39-dc2482938283.png)

Now am getting this error:
```
Traceback (most recent call last):
  File "/home/m001p596/Downloads/webportal-installer-develop/patch_web_xml.py", line 57, in <module>
    webxml = etree.parse(sys.argv[1])
  File "<string>", line 62, in parse
  File "<string>", line 38, in parse
cElementTree.ParseError: syntax error: line 1, column 0
```
![Screenshot from 2019-12-20 10-04-20](https://user-images.githubusercontent.com/40512816/71267423-1bbc5e00-2310-11ea-812f-dd0cfe2a9e83.png)

**Comment by maxxxxxdlp** [comment]
I went through all the commands make file was supposed to go through manualy and also completed other installations steps
Am getting this error when trying to open the portal
![Screenshot from 2019-12-20 10-06-40](https://user-images.githubusercontent.com/40512816/71267545-72299c80-2310-11ea-9176-66dd9750cc8a.png)

**Comment by benanhalt** [comment]
> Tried the same thing on my mac (web portal developer branch)
> <img alt="Screen Shot 2019-12-20 at 9 58 07 AM" width="1440" src="https://user-images.githubusercontent.com/40512816/71267059-4659e700-230f-11ea-93de-752767c67383.png">
> 
> Used `"pip install lxml"` to fix this issue. Now I got another problem:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/mambo/Downloads/webportal-installer-develop/patch_web_xml.py", line 35, in <module>
>     if c.tag.endswith('filter'):
> AttributeError: 'cython_function_or_method' object has no attribute 'endswith'
> make[2]: *** [web.xml] Error 1
> make[1]: *** [cores] Error 2
> make: *** [build] Error 2
> ```

This is a bug that is triggered by comments in the `web.xml` file.

**Comment by maxxxxxdlp** [comment]
Fedora 31 here

Following error when trying to execute the `"make clean && make"`
![Screenshot from 2019-12-23 10-53-39](https://user-images.githubusercontent.com/40512816/71370151-97b5e080-2572-11ea-90a9-47f2dd691d50.png)

Also was getting a lot of other errors after fixing this one manually
It was because I had both python2 and python 3 installed
This fix did not work:
```
alias python='/usr/bin/python2.7'
```
Fixed by replacing all `python` with `python2` in the following files:

- Makefile
- build.make
- core.make

Now I am again getting an error related to `lxml` library:
![Screenshot from 2019-12-23 11-12-10](https://user-images.githubusercontent.com/40512816/71370944-262b6180-2575-11ea-80c4-c3322f50a999.png)

It should be added to the list of dependencies, since this issue is present on multiple systems
> We may need to add that to the list of dependencies.

Fixed by executing the following command:
```
sudo dnf install python2-lxml
```

**Comment by maxxxxxdlp** [comment]
I am able to successfully build the web portal and access it and solr admin panel on the localhost
Yet, there is no data in the Web Portal. I tired modifying the `.csv` file, to leave no empty cells in it, deleted all the data via query and imported the csv again, with no result.
At least the columns from the csv file are properly imported.

Will do more testing to find a solution
