### ISSUE TITLE
Update copyright info

### ISSUE THREAD

**Issue by timo11** [specify/webportal-installer#48]

**Comment by maxxxxxdlp** [comment]
![Screen Shot 2020-03-26 at 12 17 49 PM](https://user-images.githubusercontent.com/40512816/77676106-d84f3c80-6f5b-11ea-9c9f-8a7ea9e2b538.png)
The year is still 2019 in the `About` page. I guess it also needs to be updated

**Comment by maxxxxxdlp** [comment]
The year is still 2018 in the `PortalApp/locale/spwp-lang-se.js`
