### ISSUE TITLE
Can't load data from export with null for latitude field

### ISSUE THREAD

**Issue by benanhalt** [specify/webportal-installer#53]
When trying to load the attached export into Solr, I get this error:
```
{
  "responseHeader":{
    "status":400,
    "QTime":24},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","java.lang.NumberFormatException"],
    "msg":"ERROR: [doc=0007f9a2-ba3b-4c4e-803b-efc2d210be0e] Error adding field 'latitude2'='null' msg=For input string: \"null\"",
    "code":400}}
```
[ShellMuseumExp.zip](https://github.com/specify/webportal-installer/files/4548403/ShellMuseumExp.zip)

**Comment by timo11** [comment]
Unfortunately this is a bug in specify6, that occurs when lat/lng2 are null but lat/lng1 are not. It looks like only about 10 rows have lat/lng2 data. So working around the problem by excision of point2 from the mapping seems OK.

**Comment by benanhalt** [comment]
Closing this in favor of the Specify 6 issue linked above.
