### ISSUE TITLE
Not loading well

### ISSUE THREAD

**Issue by rafaelmr2** [specify/webportal-installer#8]
Hi,

I using webportal in Ubuntu 16.04. 
I have recently updated webportal via git and now I pages are not loading. I tried with a new server with Debian 8 and the problem is the same. It's not cache, I have tested in other browsers. See image attached.

Thank for you help.

![specify-portal-issue](https://user-images.githubusercontent.com/4471805/35925459-eab4630a-0c0c-11e8-899b-90e6a5d54e5d.png)

**Comment by rafaelmr2** [comment]
I revert the last commit (about license) and worked.

**Comment by timo11** [comment]
Thanks for the info. We're working on it.

**Comment by timo11** [comment]
java comment got stuck in an html file. Changed it to html comment. Seems to work now.

**Comment by rafaelmr2** [comment]
It's working now. Thanks.
